### ISSUE TITLE
[refactoring] TODO list

### ISSUE THREAD

**Issue by umlsynco** [umlsynco/snippetor-marionette-gulp#13]
- [ ] Move all github related calls into the github controller
- [x] Add active repo initalization on
- [ ]  page first load (if user did not select repo)
- [x]  snippet load (check if repo was not loaded before)
- [x] Split snippet save procedure on comments and snippet
- [x] move github repo search into the separate page
- [x] selected repos - show branch if it is not "master"
- [ ] selected repos - how to highlight an absolutely empty repo
- [ ] selected repos - remove from the list

**Comment by umlsynco** [comment]
- [x] move github repo search into the separate page
- [ ] selected repos - show branch if it is not "master"
- [ ] selected repos - how to highlight an absolutely empty repo
- [ ] selected repos - remove from the list
