### ISSUE TITLE
[snippets][frontend] TODO list

### ISSUE THREAD

**Issue by umlsynco** [umlsynco/snippetor-marionette-gulp#9]
- [x] Get backbone collection of snippets on first load of Content: snippets == historyModel.comments - backbone collection of comments for file. Is is synchronized with left-side model;
- [x] History item focus: make history item selectable: highlight active history item
- [x] History collection sortable - sort history items
- [x] Sortable comments - make comments sortable insight history item (and probably outside too)
- [x] Snippets controller - add toolbox
- Save snippets
- Show/hide history items without comments
- Filter history items by name TBD
- [x] Save snippet - Preview: Show new-snippet page with comments preview

**Comment by umlsynco** [comment]
- [x] load history item on comments click if items was not in focus 
- [x] make comments update-able:
- Show snippet bubble should get pointer on historyItem model and active comment model (or new flag for example) We should not add comment to the list before user clicked "save"

**Comment by umlsynco** [comment]
- [x] insert comment after another one

**Comment by umlsynco** [comment]
- [x] next prev navigation

**Comment by umlsynco** [comment]
Added issue #10 #11 and #12
